baseurl: "http://rinpharma.com"
title: "R/Pharma"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: "UA-109863434-1"

params:
  # Conference info
  Name: "R / Pharma"
  Description: "Using R to bring medicines to patients"
  Date: "15th and 16th of August, 2018"
  #Price: "Registration closes April 1st" # If your event is free, just comment this line
  Venue: "Harvard University"
  Address: "Harvard University, CGIS South, Cambridge Street, Cambridge, MA, USA"
  City:  "Cambridge"
  State: "MA"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - speakers
    # call4papers
    - location
    - hotel
    #- schedule
    - sponsors
    #- governance
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    call4papers: "Call for papers"
    hotel: "Hotel"
    location: "Location"
    speakers: "Keynotes"
    schedule: "Schedule"
    sponsors: "Sponsors"
    governance: "Governance"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Click here to register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # List of Partners
  Governance:
    - name: "Also the R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # The entire schedule
  Schedule:

    - name: "RStudio"
      photo: "/img/MaxKuhn.jpeg"
      bio: "The tidyverse (tidyverse.org) is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. The packages primarily consist of tools for data ingest, manipulation, and visualization. In the last year or so, Rstudio and others have been creating a set of packages focused on the modeling process. In this talk, we will introduce the tidyverse and illustrate these new tools whose goals are to: simplify the modeling process, encourage empirical validation and good methodology, and to enable a wider variety of approaches."
      company: "RStudio"
      link:
        href: "https://www.linkedin.com/in/max-kuhn-864a9110"
        text: "linkedin profile"
      presentation:
        title: "Modeling in the tidyverse"
        description: "The tidyverse (tidyverse.org) is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. The packages primarily consist of tools for data ingest, manipulation, and visualization. In the last year or so, Rstudio and others have been creating a set of packages focused on the modeling process. In this talk, we will introduce the tidyverse and illustrate these new tools whose goals are to: simplify the modeling process, encourage empirical validation and good methodology, and to enable a wider variety of approaches."
        time: "Max Kuhn"

    - name: "FDA"
      photo: "/img/Lilliam.jpeg"
      bio: "Lilliam is Director of the Office of Computational Science at the FDA. Lilliam will provide a perspective on what the office of computational science is doing to support regulatory  review for safety assessments.  This includes exploring the concept of collaborations and sharing to support process and transparency bringing in a perspective of the use of R."
      company: "FDA"
      link:
        href: "https://www.fda.gov/AboutFDA/CentersOffices/OfficeofMedicalProductsandTobacco/CDER/ucm428946.htm"
        text: "Bio"
      presentation:
        title: "TBD"
        description: "Lilliam is Director of the Office of Computational Science at the FDA. Lilliam will provide a perspective on what the office of computational science is doing to support regulatory  review for safety assessments.  This includes exploring the concept of collaborations and sharing to support process and transparency bringing in a perspective of the use of R."
        time: "Lilliam Rosario"

