baseurl: "http://rinpharma.com"
title: "R/Pharma"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: "UA-109863434-1"

params:
  # Conference info
  Name: "R / Pharma"
  Description: "Using R to bring medicines to patients"
  Date: "August 21, 22, and 23, 2019 (Date TBC)"
  #Price: "Registration closes April 1st" # If your event is free, just comment this line
  Venue: "Harvard University"
  Address: "Harvard University, CGIS South, Cambridge Street, Cambridge, MA, USA"
  City:  "Cambridge"
  State: "MA"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - speakers
    # call4papers
    - location
    - hotel
    - schedule
    - sponsors
    #- governance
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    call4papers: "Call for papers"
    hotel: "Hotel"
    location: "Location"
    speakers: "Keynotes"
    schedule: "Schedule"
    sponsors: "Sponsors"
    governance: "Governance"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Click here to register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # List of Partners
  Governance:
    - name: "Also the R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # The entire schedule
  Schedule:

    - name: "RStudio"
      photo: "/img/MaxKuhn.jpeg"
      bio: "The tidyverse (tidyverse.org) is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. The packages primarily consist of tools for data ingest, manipulation, and visualization. In the last year or so, Rstudio and others have been creating a set of packages focused on the modeling process. In this talk, we will introduce the tidyverse and illustrate these new tools whose goals are to: simplify the modeling process, encourage empirical validation and good methodology, and to enable a wider variety of approaches."
      company: "RStudio"
      link:
        href: "https://twitter.com/topepos?lang=en"
        text: "Twitter"
      presentation:
        title: "Modeling in the tidyverse"
        description: "The tidyverse (tidyverse.org) is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. The packages primarily consist of tools for data ingest, manipulation, and visualization. In the last year or so, Rstudio and others have been creating a set of packages focused on the modeling process. In this talk, we will introduce the tidyverse and illustrate these new tools whose goals are to: simplify the modeling process, encourage empirical validation and good methodology, and to enable a wider variety of approaches."
        time: "Max Kuhn"

    - name: "FDA"
      photo: "/img/Lilliam.jpeg"
      bio: "Lilliam will be presenting a perspective on what the office of computational science is doing to support regulatory review for safety assessments. She will explore the concept of collaborations and sharing to support process and transparency, along with a perspective with the use of R."
      company: "FDA"
      link:
        href: "https://www.fda.gov/AboutFDA/CentersOffices/OfficeofMedicalProductsandTobacco/CDER/ucm428946.htm"
        text: "Bio"
      presentation:
        title: "Modernizing the new drug regulatory program in FDA/CDER:  Can Collaborations and Sharing Help?"
        description: "Lilliam will be presenting a perspective on what the office of computational science is doing to support regulatory review for safety assessments. She will explore the concept of collaborations and sharing to support process and transparency, along with a perspective with the use of R."
        time: "Lilliam Rosario"

    - name: "Roche/Genentech"
      photo: "/img/michael.jpeg"
      bio: "The open-source analytics community is driving innovation in precompetitive spaces like statistical methodology, reproducibility approaches, visualization techniques, and scaling strategies. The diverse and rapidly evolving ecosystem of open-source tools and standards stands in contrast with the disposition of the enterprise towards stability, standardization, and reliability. This talk will present the policies and frameworks we have developed at Genentech to enable internal scientists to responsibly leverage open-source tools and to participate in the community process through their own contributions."
      company: "Roche/Genentech"
      link:
        href: "https://twitter.com/lawremi?lang=en"
        text: "Twitter"
      presentation:
        title: "Enabling open-source analytics in the enterprise"
        description: "The open-source analytics community is driving innovation in precompetitive spaces like statistical methodology, reproducibility approaches, visualization techniques, and scaling strategies. The diverse and rapidly evolving ecosystem of open-source tools and standards stands in contrast with the disposition of the enterprise towards stability, standardization, and reliability. This talk will present the policies and frameworks we have developed at Genentech to enable internal scientists to responsibly leverage open-source tools and to participate in the community process through their own contributions."
        time: "Michael Lawrence"

    - name: "RStudio"
      photo: "/img/joecheng.jpeg"
      bio: "Shiny is a package for turning analyses written in R into interactive web applications. This capability has obvious applications in pharma, as it lets R users build interactive apps for their collaborators to explore models or results, or to automate workflows. However, the interactivity of Shiny apps is a double-edged sword, as it introduces challenges to the traceability and reproducibility of your analysis. To use interactive applications in pharma responsibly, these challenges must be addressed. In this talk, I'll look at some of the tools and techniques you can use in Shiny to deal with these challenges head-on."
      company: "RStudio"
      link:
        href: "https://twitter.com/jcheng?lang=en"
        text: "Twitter"
      presentation:
        title: "Using interactivity responsibly in pharma"
        description: "Shiny is a package for turning analyses written in R into interactive web applications. This capability has obvious applications in pharma, as it lets biostatisticians build interactive apps for their collaborators to explore models or results, or to automate workflows. However, the interactivity of Shiny apps is a double-edged sword, as it introduces challenges to the traceability, reproducibility, and integrity of your analysis. To use interactive applications in pharma responsibly, these challenges must be addressed. In this talk, I'll look at some of the tools and techniques you can use in Shiny to deal with these challenges head-on."
        time: "Joe Cheng"
